package org.example.dto;

public enum RequestAction {
    GET_BUDGET_AMOUNT,
    GET_USER_OPERATIONS,

    INCREASE_OPERATION,
    DECREASE_OPERATION,
    GET_RECENT_OPERATIONS,
    UPDATE_OPERATION,
    DELETE_OPERATION,
    GET_FILTERED_OPERATIONS,

    SIGN_UP,
    SIGN_IN,
}
