jwt.access.validityInSeconds=3600
jwt.refresh.validityInSeconds=86400
logging.level.root=INFO
logging.level.org.example.application.service=DEBUG
logging.level.org.example.domain.dao=DEBUG
logging.level.org.example.infrastructure.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/application.log
logging.file.max-size=10MB
logging.file.max-history=30