package org.example.dto.request;

public enum RequestAction {
    GET_HOUSEHOLD_AMOUNT,

    GET_USER_OPERATIONS,

    CREATE_OPERATION,
    GET_FILTERED_OPERATIONS,
    GET_RECENT_OPERATIONS,
    UPDATE_OPERATION,
    DELETE_OPERATION,

    CREATE_HOUSEHOLD,
    UPDATE_HOUSEHOLD,
    DELETE_HOUSEHOLD,

    CREATE_HOUSEHOLD_MEMBER,
    UPDATE_HOUSEHOLD_MEMBER_ROLE,
    DELETE_HOUSEHOLD_MEMBER,

    UPDATE_USER,

    CREATE_ACCOUNT,
    GET_ACCOUNTS,
    GET_ACCOUNT,
    DELETE_ACCOUNT,

    CREATE_ACCOUNT_MEMBER,
    UPDATE_ACCOUNT_MEMBER_ROLE,
    DELETE_ACCOUNT_MEMBER,

    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    GET_CATEGORIES,
    GET_INCOME_CATEGORIES,
    GET_EXPENSE_CATEGORIES,
    DELETE_CATEGORY,

    SIGN_UP,
    SIGN_IN,
    LOGOUT,
}
