package org.example.request;

public enum RequestAction {
    CREATE_OPERATION,
    GET_FILTERED_OPERATIONS,
    GET_ACCOUNT_OPERATIONS,
    GET_HOUSEHOLD_OPERATIONS,
    GET_MY_OPERATIONS,
    UPDATE_OPERATION,
    DELETE_OPERATION,

    CREATE_HOUSEHOLD,
    GET_HOUSEHOLD,
    GET_HOUSEHOLD_AMOUNT,
    UPDATE_HOUSEHOLD,
    DELETE_HOUSEHOLD,

    CREATE_HOUSEHOLD_MEMBER,
    UPDATE_HOUSEHOLD_MEMBER_ROLE,
    DELETE_HOUSEHOLD_MEMBER,

    CREATE_ACCOUNT,
    GET_MY_ACCOUNTS_IN_HOUSEHOLD,
    GET_ACCOUNT,
    UPDATE_ACCOUNT,
    DELETE_ACCOUNT,

    CREATE_ACCOUNT_MEMBER,
    UPDATE_ACCOUNT_MEMBER_ROLE,
    DELETE_ACCOUNT_MEMBER,

    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    GET_CATEGORIES,
    GET_INCOME_CATEGORIES,
    GET_EXPENSE_CATEGORIES,
    DELETE_CATEGORY,

    SIGN_UP,
    SIGN_IN,
    LOGOUT,
    GET_USER,
    GET_ME,
    UPDATE_USER,
    DELETE_MY_USER,
    REFRESH_TOKENS,

}
